name: lint check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install black and isort and mypy flake8
        run: pip install black isort mypy flake8

      - name: Run black
        run: black --check --diff .

      - name: Run isort
        run: isort --diff .

      - name: Run mypy
        run: mypy .

      - name: Run flake8
        run: flake8 .
