# GitHub Action that uses Black to reformat the Python code in an incoming pull request.
# If all Python code in the pull request is compliant with Black then this Action does nothing.
# Othewrwise, Black is run and its changes are committed back to the incoming pull request.
# https://github.com/cclauss/autoblack

name: autoblack
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install black and isort and mypy
        run: pip install black isort mypy

      - name: Run black
        run: black --check --diff .

      - name: Run isort
        run: isort --profile black --diff .

      - name: Run mypy
        run: mypy --ignore-missing-imports --exclude src/components/volume/windows_vol.py .
